# pull official base image
FROM node:19

# set working directory
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH
ENV NODE_ENV development

# install and cache app dependencies
COPY package.json .
COPY package-lock.json .
RUN npm ci
RUN npm install react-scripts@5.0.1 prettier@2.8.4 eslint@8.35.0 -g --silent

# add app
COPY . .

# start app
CMD ["npm", "start"]